### ISSUE TITLE
2.7 Release checklist

### ISSUE THREAD

**Issue by poshul** [OpenMS/OpenMS#5402]
Release preparation instructions from: https://github.com/OpenMS/OpenMS/wiki/Preparation-of-a-new-OpenMS-release#release_manager

- [x] Preparing the release candidate
   - [x] Check all the issues labeled with a Release milestone and fix/implement or postpone/relabel them.
   - [x] Check for and fix release critical/blocker issues on GitHub (in all repositories if possible)
   - [x] Check and fix automatic tests on all platforms (= nightlies)
   - [x] Check and fix or at least reduce compile warnings in CDASH
   - [x] Check if all examples in OpenMS/doc/code_examples/ compile.
   - [x] Check and fix static code and style analysis
        1. cpplint violations (can be fixed with uncrustify, check if new version of tool exists - report as issue if so)
        1. cppcheck (in general manually fixed, check if newer version of tool exists - report as issue if so)
        1. Check and fix checker.php script violations
        1. Check and fix pyOpenMS failed tests
        1. **TO FINISH:** Spelling (use spell checker script in tools)
   - [x] Update the CHANGELOG file with the changed tool parameters (use tools/changelog_helper.sh script)
   - [x] Update year numbers in:
        1. /cmake/knime/COPYRIGHT
        1. All headers and cpp files and License.txt and LICENSE (see the update_header_dates.sh script in the tools folder)
   - [x] Double-check Version Number (should have been updated on develop after the last release) in:
        1. CMakeLists.txt of OpenMS (three OPENMS_PACKAGE_VERSION_* variables, and the contrib version check)
          
           ```
              set(OPENMS_PACKAGE_VERSION_MAJOR "2")
              set(OPENMS_PACKAGE_VERSION_MINOR "0")
              set(OPENMS_PACKAGE_VERSION_PATCH "1")
           ```
        1. In /src/tests/class_tests/openms/source/VersionInfo_test.cpp the method test:    
           ```
              START_SECTION((static VersionDetails getVersionStruct()))
           ```
        1. In source/src/tests/topp/WRITE_INI_OUT.ini and src/tests/topp/INIUpdater_1_noupdate.toppas
        1. Optionally in the ini files of the tests in OpenMS/src/tests/topp/ (gets rid of warnings during tests. Might use a script in the future)
        1. In `src/pyOpenMS/doc/Manual.tex`

   - [x] Update the list of active maintainers in tools/ACTIVE_MAINTAINERS
   - [x] Check if new developers added themself to the list of authors in AUTHORS
   - [x] Check if novel tools are listed in TOPPToolHandler and in ToolsDialog (if applicable)
   - [x] Check if tutorial.html#tutorial_library_overview is up-to-date
   - [x] Update the ${CURRENTYEAR}.bib files on our Wordpress instance with novel publications by logging in, clicking on OpenMS in the upper left, selecting Media (on the left), searching for ${CURRENTYEAR}.bib, saving and deleting it if present and re-uploading an updated version. Add them to https://scholar.google.de/citations?user=tQ26gxIAAAAJ&hl=en, too.
   - [x] Run the Python extension checker to ensure that the public API is accessible through the pyOpenMS Python wrapper. 
        1. Run the doc target `make doc_xml`
        1. Identify missing wrappers:

            1. Run the checker (this assumes running it in the source folder, not the build folder): 

            ```
            $ mkdir pxd_out_folder
            $ python tools/PythonExtensionChecker.py --bin_path ../../builds/openms/ --src_path . \
              --ignore-file tools/pychecker_ignore.yaml --pxds-out pxd_out_folder
            [...]
            Parsed public methods 4752 (of which were missing 910 and 730 were operator/destructors)
              - wrapped 3842
              - unwrapped operators/destructors 730
              - unwrapped methods 180
            [...]
            - Could not find associated pxd file : 27
            - Could not find matching class in pxd file : 7
            ```
   
            1. The above output indicates that there are 180 methods that are currently not wrapped and 34 classes that are not wrapped at the moment (for these classes, you can use the `pxd` files in `pxd_out_folder` as starting point for wrapping). Note that it will complain about missing classes/methods that are not wrapped unless they are explicitly marked as not part of the public API in `tools/pychecker_ignore.yaml`
        1. Add missing classes either to the `tools/pychecker_ignore.yaml` file or add the corresponding `pxd` file from `pxd_out_folder` to `src/pyOpenMS/pxds/` (potentially some manual assembly required)
   - [x] Create the release branch (e.g.: release/2.3.0) from current develop. This will trigger RC build jobs on jenkins for every push. Fix e.g. remaining installer/packaging issues on that branch (see next step for what a successful installer needs to fulfill).
   - [x] Increment the version number on develop to signal the start of the new development cycle.

- [x] Organize packaging/installers (check release candidates [here](https://abibuilder.informatik.uni-tuebingen.de/archive/openms/OpenMSInstaller/RC/) )
   - [ ] Check if all bundled VC redistributables match the visual studio version of OpenMS AND third party tools
   - [x] Check if [prerequisites installer](https://abibuilder.informatik.uni-tuebingen.de/archive/openms/OpenMSInstaller/PrerequisitesInstaller) used by KNIME to fetch missing packages bundles the correct VC redistributables
   - [x] Check version and potentially update third party executables (e.g. proteowizard). Be careful not to break anything (happens easily if search engines are updated). Do not forget to update the License.txt of OpenMS concerning links and licenses of the Thirdparty tools.
   - [x] Make sure the binary installer/packages are built for all platforms, also in KNIME (e.g. MyriMatch)
   - [x] Check OpenMS installation on target platforms and KNIME: https://github.com/OpenMS/OpenMS/wiki/Testing-a-OpenMS-release-candidate
   - [ ] Update bioconda recipe to build from the RC of OpenMS-X.X.X-src.tar.gz by opening a new PR to bioconda and make sure it builds (do not let it merge yet).
- [x] Test and update (!) KNIME tutorial workflows in the Tutorials repository as some parameters might have been removed or changed. This usually requires replacing a node (which still has the old parameters) with the corresponding KNIME node from the new release (drag&drop on top of it). Please make sure that you adapted all parameters (including advanced ones) to match the ones used with the old node. Please adapt the Tutorial handout, too, if necessary (usually at least the version numbers).
    1. You can try the Workflow comparison tool for that (right-click on the workflows)
- [ ] Tag, deploy and announce
   - [x] Start the openms/release job on Jenkins for the version you want to release (usually with latest=True and announce=True). This will copy the RC to release folders, create md5sums and softlink the latest release. It will also try to create a draft release with attached assets on GitHub and a news draft on www.openms.de.
   - [x] Make sure it finished successfully and created tags on all important OpenMS and GWN repos (contrib, THIRDPARTY, Tutorials,...), as well as drafts for a 
Release (with asset and correct target branch master or release/*) on the OpenMS repo and the OpenMS homepage news. Check that master is in sync with the release branch and tagged as well.
   - [x] Check the softlinks on the build archive.
   - [x] Make sure that the GitHub action for a pyopenms release was triggered and successful.
   - [x] Update the pyopenms version in the pyopenms documentation ([https://github.com/OpenMS/pyopenms-extra/](https://github.com/OpenMS/pyopenms-extra/))
   - [ ] Optionally update bioconda PR to use the release asset from GitHub instead of archive link. After successful build: Comment "@Bioconda-Bot please fetch artifacts" (or equivalent) and test the artifacts with (replace versions):

       ```bash
       for py in 3.6 3.7 3.8 do
         conda create -n openmscondatest-$py python=$py
         conda install -c https://${FULLINK_SEE_PR}-gh.circle-artifacts.com/0/tmp/artifacts/packages -c bioconda -c conda-forge openms-thirdparty=$VERSION pyopenms=$VERSION
         conda activate openmscondatest-$py
         OpenMSInfo
         python -c "import pyopenms"
         conda deactivate
       done
       ```

   - [ ] If tests are successful comment "@Bioconda-Bot please add label" and wait for a review of the bioconda maintainer. Then merge.
   - [x] Merge changes on the release/master branch back to develop
   - [ ] Make sure that after a successful build of the community contributions on the KNIME Jenkins (e.g. https://community.knime.org/jenkins/job/de.openms.knime.update-trunk/ and latest release) to label the last build of the old version as "Keep forever" (upper right of the overview page of a specific build) and tag it with the released version number of OpenMS (so that it is selectable as an alternative in KNIME (when "Show old version" is activated) for older workflows once this release is outdated. KNIME should automatically fetch the new plugin, once it is softlinked to release/latest on our archive.
   - [ ] Upload the installers to sourceforge (e.g. sftp to SFUSER@frs.sourceforge.net/home/pfs/project/o/op/open-ms/OpenMS/RELEASE_NAME )
   - [x] Create a release of the OpenMS/Tutorial for the current version tag and attach https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Tutorials/Handout/master/*.pdf
   - [ ] Post news to Website and Social Media (check that there are no links to old docu or downloads, otherwise make it point to "latest")
        1. http://www.openms.de/download/knime-plugin/
        1. http://www.openms.de/download/openms-sources/
        1. http://www.openms.de/download/openms-binaries/
        1. Announce on "OpenMS Team" twitter account
        1. Approve the draft of the "News" item of the OpenMS webpage if auto-generation worked or create one manually.
   - [ ] Check if still current (and update) "Supported Platforms" on main OpenMS webpage
   - [ ] Send a mail notification to the announcements mailing list and the general mailing list
   - [ ] Update the OpenMS wikipedia.org site https://en.wikipedia.org/wiki/OpenMS
   - [x] Create an update openms_versions.txt file used by the REST server (abibuilder0) during update checks (use tools/rest_server_update_helper.sh)
and update https://github.com/OpenMS/usage_plots/blob/master/openms_versions.txt
- [x] Check links in OpenMS Developer tutorial (how to build OpenMS) and update them if needed
        `doc/OpenMS_tutorial/OpenMS_Tutorial.doxygen`

**Comment by oliveralka** [comment]
Note: 
Try to update Doxygen after Release 2.7 (doxygen -u). It seems some of the configurations is outdated.

**Comment by poshul** [comment]
KNIME tutorial workflows should all work after https://github.com/OpenMS/OpenMS/pull/5529 on Windows. There is an outstanding issue with the paths in two QC workflows (See: https://github.com/OpenMS/OpenMS/issues/5530) when using absolute paths in linux, and Comet still crashes on linux.
