### ISSUE TITLE
Run C++ code examples as Jupyter Notebooks on Binder/Google Collab (whichever works)

### ISSUE THREAD

**Issue by tapaswenipathak** [OpenMS/OpenMS#6304]
## Problem Statement

A detailed example of how code snippets in the OpenMS C++ manual can be made executable on Xeus-Cling, Jupyter, Binder. This is similar to the Binder integration of the pyOpenMS code on https://pyopenms.readthedocs.io/en/latest/. The example includes the packaging of the OpenMS library and its dependencies and allows for exemplary data files to be uploaded and executed on Binder. The maintainability of the solution is guaranteed by generating notebooks from OpenMS’ example.cpps every night automatically in a separate repo and using the nightly conda.

## Sub Tasks

Sub tasks | Discussion/Decision | Remarks
-- | -- | --
UI | Strong preference for Binder w/ xeus-cling | Binder (if not) → Google Collab, build timeout, extensibility
Data | https://github.com/OpenMS/OpenMS/tree/develop/doc/code_examples/data | later: https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Tutorials/Data/latest/Example_Data/Introduction/datasets/tiny/
Code Examples | https://github.com/OpenMS/OpenMS/tree/develop/doc/code_examples | 
Add link to openms.readthedocs.io |  ? | ?
Maintainability of your solution should be guaranteed by generating notebooks from OpenMS’ example.cpps every night automatically in a separate repo and using the nightly conda. |  cling-notebooks (@jpfeuffer @tjeerdijk) | separate repo? openms-docs? images of build of binder goes to separate repository name or branch of openms-docs/openms
How to use https://mybinder.org/v2/gh/OpenMS/pyopenms-extra/master+ipynb?urlpath=lab/tree/docs/source/index.ipynb? |   datastructures_peak.ipynb | ![](https://uc17c48a8e988312b68e4b37deda.previews.dropboxusercontent.com/p/thumb/ABqIoUXdap_oW1LRIEDkz9EiJ0SRvas_znsR9y1EUziaLva9OBHgPQ3eNZCWDWM8qJ9gJjzY5xJB6dimhmVPP_CjhZ4-pIn-EGB4yC3fpoAS8ULNfoauz_sZwcE4X_w2p9Yeaq-z_oLP0-gQKKI3iu9tzSOZkBARpIWeSPT4voTZraZ0S9zd4IIBjdgF-Og4lasspG9FunXqGMyc7WWJbjf2RgJfelG63oLctAk7blIh1rJeW8UtlV2ggFkgIxRLvWZ8JslfDR-J-C7oufgKzaknPA4yfk5dCOxzGiSWruWhHAVprnoFaDR3BNeJRrM8HwL8MSdF8yfH2eoGQaIOFSAurX08FI4AW-iiWNOf-vAd3POxn_uxz5pTSivLGESwKk8Br8oFJlMVSG3qtTll4At3BDqeFDJwAX-liqJX0YfcVEXJGRfncn4RbdlTZWKF_P0/p.png)

## TODO

- [x] Create repository `OpenMS/cling-notebooks`
- [ ] Create OpenMS on Binder or connect cling-notebooks
- [ ] Test run on Binder Xeus-Cling
- [ ] Publish to cling-notebooks
- [ ] Republish to cling-notebooks
- [ ] CRUD and publish to cling-notebooks
- [ ] Optional: Example page on [openms-docs](https://openms.readthedocs.io/en/develop) about run on Binder/Google Collab
- [ ] Cron every night to publish nightly notebooks
- [ ] README badges (if any)

## Focus Points

- [ ] Timeout issue of building OpenMS/OpenMS (yes/no, `.deb`)
- [ ] Extensibility
- [ ] Heavy data?
     - https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Tutorials/Data/latest/Example_Data/Introduction/datasets/tiny/
- [ ] load time

cc @tjeerdijk.

**Comment by timosachsenberg** [comment]
I added you to the repo
