### ISSUE TITLE
Release checklist for 3.2.0

### ISSUE THREAD

**Issue by poshul** [OpenMS/OpenMS#7123]
Release preparation instructions from: https://github.com/OpenMS/OpenMS/wiki/Preparation-of-a-new-OpenMS-release#release_manager

- [x] Preparing the release candidate
   - [x] Check all the issues labeled with a Release milestone and fix/implement or postpone/relabel them.
   - [x] Check for and fix release critical/blocker issues on GitHub (in all repositories if possible)
   - [x] Check and fix automatic tests on all platforms ([= nightlies](https://github.com/OpenMS/OpenMS/actions/workflows/openms_ci_matrix_full.yml?query=branch%3Anightly))
   - [x] (Optional: Update the [CHANGELOG_PARAMS](https://github.com/OpenMS/OpenMS/blob/develop/CHANGELOG_PARAMS) file with the changed tool parameters (use tools/changelog_helper.sh script)
   - [x] Double-check year numbers (should have been updated by the GitHub Action https://github.com/OpenMS/OpenMS/actions/workflows/update_version_numbers.yml every year) in:
        1. /cmake/knime/COPYRIGHT
        1. All headers and cpp files and License.txt and LICENSE (see the update_header_dates.sh script in the tools folder)
   - [x] Double-check Version Number (should have been updated on develop after the last release, with the [GitHub Action](https://github.com/OpenMS/OpenMS/actions/workflows/update_version_numbers.yml)) in:
        - [x] CMakeLists.txt of OpenMS (three OPENMS_PACKAGE_VERSION_* variables, and the contrib version check)
          
           ```
              set(OPENMS_PACKAGE_VERSION_MAJOR "2")
              set(OPENMS_PACKAGE_VERSION_MINOR "0")
              set(OPENMS_PACKAGE_VERSION_PATCH "1")
           ```
        - [x] In `src/tests/class_tests/openms/source/VersionInfo_test.cpp` the method test:    
           ```
              START_SECTION((static VersionDetails getVersionStruct()))
           ```
        - [x] `src/tests/topp/WRITE_INI_OUT.ini`
        - [x] `src/tests/topp/INIUpdater_1_noupdate.toppas`
        - [x] Update the pyopenms version in the pyopenms documentation ([conf.py](https://github.com/OpenMS/pyopenms-docs/blob/master/docs/source/conf.py#L85) [switcher.json](https://github.com/OpenMS/pyopenms-docs/blob/master/docs/source/_static/switcher.json)) → https://github.com/OpenMS/pyopenms-docs/pull/440
        - [x] Update the version in the openms documentation ([conf.py](https://github.com/OpenMS/OpenMS-docs/blob/develop/docs/conf.py)) → https://github.com/OpenMS/OpenMS-docs/pull/234

   - [x] (Optional: Update the list of active maintainers in [tools/ACTIVE_MAINTAINERS](https://github.com/OpenMS/OpenMS/blob/develop/tools/ACTIVE_MAINTAINERS) )
   - [x] Check if new developers added themself to the list of authors in [AUTHORS](https://github.com/OpenMS/OpenMS/blob/develop/AUTHORS) → https://github.com/OpenMS/OpenMS/pull/7538
   - [x] Check if novel tools are listed in [TOPPToolHandler ](https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/APPLICATIONS/ToolHandler.cpp) - see next step
   - [x] Check the doxygen documentation at https://openms.de/current_doxygen/
       - [x] Check all new tools are properly linked and do not show up on the ['Related Pages' section](https://openms.de/current_doxygen/html/pages.html)
       - [x] Check installation instructions for all three platforms are up-to-date, especially package names for current Linux distros
   - [x] Check if [tutorial.html#tutorial_library_overview ](https://github.com/OpenMS/OpenMS/blob/develop/doc/doxygen/public/developer_tutorial.doxygen) is up-to-date
   - [x] Check if library version (e.g., ["Qt 5.9"](https://github.com/OpenMS/OpenMS/blob/develop/cmake/cmake_findExternalLibs.cmake), [minimum cmake version](https://github.com/OpenMS/OpenMS/blob/develop/CMakeLists.txt) mentioned in build instructions for [linux](https://github.com/OpenMS/OpenMS/blob/develop/doc/doxygen/install/install-linux.doxygen), [mac](https://github.com/OpenMS/OpenMS/blob/develop/doc/doxygen/install/install-macs.doxygen), and [windows](https://github.com/OpenMS/OpenMS/blob/develop/doc/doxygen/install/install-win.doxygen) match to requirements in cmake files.
   - [x] Check version and potentially update third party executables (https://github.com/OpenMS/THIRDPARTY) (e.g. proteowizard, search engines like comet). Be careful not to break anything (happens easily if search engines are updated. You will most likely see failing tests or changed output files). Do not forget to update the License.txt of OpenMS concerning links and licenses of the Thirdparty tools. Also note that you might need to update the search engine version in other places like the conda recipe for thirdparty tools.
   - [x] Create the release branch (e.g.: release/2.3.0) from current develop. This will trigger the package and KNIME build jobs on git hub actions for every push. Fix e.g. remaining installer/packaging issues on that branch (see next step for what a successful installer needs to fulfill).
   - [x] Increment the version number on develop to signal the start of the new development cycle by triggering the GitHub Action manually.

- [x] Organize packaging/installers (check release candidates [here](https://abibuilder.cs.uni-tuebingen.de/archive/openms/OpenMSInstaller/Release/RC/) )
   - [x] Check if all bundled VC redistributables match the visual studio version of OpenMS AND third party tools
   - [x] Check version and potentially update third party executables (e.g. proteowizard). Be careful not to break anything (happens easily if search engines are updated). Do not forget to update the License.txt of OpenMS concerning links and licenses of the Thirdparty tools.
   - [x] Make sure the binary installer/packages are built for all platforms
   - [x] Check OpenMS installation on target platforms (this includes running a few TOPP tools and TOPPView after installation)
   - [x] upload the Windows installer to https://www.microsoft.com/en-us/wdsi/filesubmission, to clear its SmartScreen warning (see https://github.com/OpenMS/OpenMS/issues/6776#issuecomment-1833905827)
   - [x] Update bioconda recipe to build from the Release of OpenMS-X.X.X-src.tar.gz by opening a new PR to bioconda and make sure it builds (do not let it merge yet).
- [ ] Tag, deploy and announce
Run the [openms-ci-full](https://github.com/OpenMS/OpenMS/actions/workflows/openms_ci_matrix_full.yml) action manually using the run workflow button. Select "Build and upload packages/installer/documentation? ", " Build and upload KNIME plugins and update site?, "Make tags and create a github release? ", "Update latest to point to this release ", and "Update website and create announcement material for release".
    1. Make sure it finished successfully and created tags on:
        1. [OpenMS/contrib](https://github.com/OpenMS/contrib/tags)
        1. [OpenMS/pyopenms-docs](https://github.com/OpenMS/pyopenms-docs/tags)
        1. [OpenMS/THIRDPARTY](https://github.com/OpenMS/THIRDPARTY/tags)
        1. [OpenMS/Tutorials](https://github.com/OpenMS/Tutorials/tags)
        1. [OpenMS/OpenMS-docs](https://github.com/OpenMS/OpenMS-docs/tags)
        1. [OpenMS/de.openms.knime](https://github.com/OpenMS/de.openms.knime/tags)
   - [x]  Check the softlinks on the buildarchive for the [installer](https://abibuilder.cs.uni-tuebingen.de/archive/openms/OpenMSInstaller/release/latest/) and the [knime-plugin](https://abibuilder.cs.uni-tuebingen.de/archive/openms/knime-plugin/updateSite/release/latest/).
   - [ ] Make sure that the GitHub action for a pyopenms pypi build was [triggered and successful](https://github.com/OpenMS/OpenMS/actions/workflows/pyopenms-wheels.yml).
   - [x] Edit the OpenMS recipe (https://github.com/bioconda/bioconda-recipes/blob/master/recipes/openms-meta/meta.yaml). You typically need to update version number, checksum, thirdparty tools (if you support e.g., a newer version of a search engine) and dependencies (if some have been added or removed in OpenMS). After a successful build on the bioconda infrastructure: Comment "@Bioconda-Bot please fetch artifacts" (or equivalent) and test the artifacts with (replace versions):

       ```bash
       for py in 3.8 3.9 3.10 3.11 do
         conda create -n openmscondatest-$py python=$py
         conda install -c https://${FULLINK_SEE_PR}-gh.circle-artifacts.com/0/tmp/artifacts/packages -c bioconda -c conda-forge openms-thirdparty=$VERSION pyopenms=$VERSION
         conda activate openmscondatest-$py
         OpenMSInfo
         python -c "import pyopenms"
         conda deactivate
       done
       ```

   - [ ] If local tests of the artefacts are successful comment "@Bioconda-Bot please add label" and wait for a review of the bioconda maintainer. Then merge.
   - [x] Merge changes on the release/x.x.x branch back to develop
   - [ ]    1. Post news to Website and Social Media (check that there are no links to old docu or downloads, otherwise make it point to "latest"). 
        1. Approve the PR for the [OpenMS webpage](https://github.com/OpenMS/OpenMS-website/pulls)
   - [ ] Check if still current (and update) "Supported Platforms" on main OpenMS webpage
   - [ ] Send a mail notification to the announcements mailing list and the general mailing list with the announcement text 
   - [ ] Update the OpenMS wikipedia.org site https://en.wikipedia.org/wiki/OpenMS
- [ ] Check links in OpenMS Developer tutorial (how to build OpenMS) and update them if needed
        `doc/OpenMS_tutorial/Developer_Tutorial.doxygen`

**Comment by timosachsenberg** [comment]
need update: 
- we have an action for version number update https://github.com/OpenMS/OpenMS/blob/develop/.github/workflows/update_version_numbers.yml

**Comment by cbielow** [comment]
I also edited some stuff in the list above. Let's make sure we use this list as a template for the next release after 3.2

**Comment by mr-c** [comment]
> [ ] Check for and fix release critical/blocker issues on GitHub (in all repositories if possible)

Which repos?

> [ ]  Update the list of active maintainers in tools/ACTIVE_MAINTAINERS

By what criteria? Just email around and ask?

> [ ] Check if new developers added themself to the list of authors in AUTHORS

Needs a script ~~+ `.mailmap` file~~
(I ended up using `git log  Release3.1.0...HEAD --pretty="%aN <%aE>" | sort -u | less` )

> [ ] Increment the version number on develop to signal the start of the new development cycle.

This didn't happen previously :-(

**Comment by mr-c** [comment]
https://github.com/OpenMS/OpenMS/wiki/Preparation-of-a-new-OpenMS-release says to use `ENABLE_TUTORIALS=ON` but that was removed in https://github.com/openMS/openMS/commit/96b9c58ce77018c7341cb7ae3fbe7706b8f3cab7 ; is there a replacement?

**Comment by timosachsenberg** [comment]
@cbielow

**Comment by poshul** [comment]
> TUTORIALS

Those have gotten moved out to a separate repo, so it's now not part of the release process.

**Comment by timosachsenberg** [comment]
are you sure? @poshul can you link to that? I thought they might be part of the doxygen documentation? I think he is talking about the compiled C++ tutorials
e.g. https://github.com/OpenMS/OpenMS/blob/develop/doc/code_examples/Tutorial_MSChromatogram.cpp

**Comment by mr-c** [comment]
In the "prepare the release candidate section" ; am I updating the version numbers to "3.2.0" or with a release candidate suffix like "3.2.0-rc1" or similar?

**Comment by mr-c** [comment]
https://github.com/OpenMS/OpenMS/blob/0fad2088f05c24840cc903425ae2c9de0820fc6d/src/tests/topp/INIUpdater_1_noupdate.toppas#L4 still has "3.1.0" ; was that supposed to have been updated by https://github.com/OpenMS/OpenMS/actions/workflows/update_version_numbers.yml ?

**Comment by poshul** [comment]
> are you sure? @poshul can you link to that? I thought they might be part of the doxygen documentation? I think he is talking about the compiled C++ tutorials e.g. https://github.com/OpenMS/OpenMS/blob/develop/doc/code_examples/Tutorial_MSChromatogram.cpp

ENABLE_TUTORIALS was just for the LaTeX pdf versions of the tutorials (see https://github.com/OpenMS/OpenMS/blob/b59e0c327902244e70413d156eeb70b193b71d90/CMakeLists.txt#L85C76-L85C81), for the example C++ code the argument is BUILD_EXAMPLES https://github.com/OpenMS/OpenMS/blob/0fad2088f05c24840cc903425ae2c9de0820fc6d/doc/CMakeLists.txt#L380

**Comment by poshul** [comment]
> In the "prepare the release candidate section" ; am I updating the version numbers to "3.2.0" or with a release candidate suffix like "3.2.0-rc1" or similar?

I think you can just use 3.2.0

**Comment by timosachsenberg** [comment]
awesome finds... 
will missing things in the wiki flow back to https://github.com/OpenMS/OpenMS/wiki/Preparation-of-a-new-OpenMS-release or do we collect this somewhere else?

**Comment by mr-c** [comment]
> awesome finds...

Thanks! But still several items needs fixing at https://github.com/OpenMS/OpenMS/issues/7123#issuecomment-2203719158 and https://github.com/OpenMS/OpenMS/issues/7123#issuecomment-2205795876

> will missing things in the wiki flow back to https://github.com/OpenMS/OpenMS/wiki/Preparation-of-a-new-OpenMS-release or do we collect this somewhere else?

I recommend doing that, yes

@timosachsenberg @poshul The uploads are timing out: https://github.com/OpenMS/OpenMS/actions/runs/9849804996/job/27207010490

**Comment by cbielow** [comment]
i added 

```
Check the doxygen documentation at https://openms.de/current_doxygen/
Check all new tools are properly linked and do not show up on the ['Related Pages' section](https://openms.de/current_doxygen/html/pages.html)
Check installation instructions for all three platforms are up-to-date, especially package names for current Linux distros
```
to the checklist above. This needs to flow back to  https://github.com/OpenMS/OpenMS/wiki/Preparation-of-a-new-OpenMS-release . Or shall we try to keep both in sync right now?

**Comment by mr-c** [comment]
> This needs to flow back to https://github.com/OpenMS/OpenMS/wiki/Preparation-of-a-new-OpenMS-release . Or shall we try to keep both in sync right now?

Lets try to sync that now; we'll do a final sync at the end as well. Thanks!

**Comment by cbielow** [comment]
ok. done.
